# Generated by Django 4.2.2 on 2023-06-10 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Recipe-Name')),
                ('type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('COFFEE', 'Coffee'), ('DINNER', 'Dinner')], max_length=120)),
                ('thumbnail', models.ImageField(default='recipe_thumbnail/default.png', upload_to='recipe_thumbnail')),
            ],
        ),
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('direction', models.CharField(max_length=120, verbose_name='Direction')),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Name')),
                ('recipe', models.ManyToManyField(to='api.recipe')),
            ],
        ),
    ]
